name: update-pr
description: Easily update PR descriptions from GitHub workflows
author: Vladimir Blagojevic
branding:
  icon: git-pull-request
  color: blue
inputs:
  pr-body:
    description: The new body text for the pull request
    required: true
  pr-number:
    description: The number of the pull request to update
    required: false # If not provided, the action will use the pull request number from the context
  token:
    description: Personal Access Token for GitHub API (if not provided, defaults to GITHUB_TOKEN)
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      env:
        PR_BODY: ${{ inputs.pr-body }}
        INPUT_PR_NUMBER: ${{ inputs.pr-number }}
        CONTEXT_PR_NUMBER: ${{ github.event.number }}
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        script: |
          const token = process.env.GITHUB_TOKEN || secrets.GITHUB_TOKEN;
          const octokit = github.getOctokit(token);
          
          const body = process.env.PR_BODY;
          const prNumber = process.env.INPUT_PR_NUMBER || process.env.CONTEXT_PR_NUMBER;

          await octokit.rest.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber,
            body: body
          });
