name: update-pr
description: Easily update PR descriptions from actions
author: Vladimir Blagojevic
branding:
  icon: git-pull-request
  color: blue
inputs:
  pr-body:
    description: The new body text for the pull request
    required: true
  pr-number:
    description: The number of the pull request to update
    required: false # If not provided, the action will use the pull request number from the context

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      env:
        PR_BODY: ${{ inputs.pr-body }}
        INPUT_PR_NUMBER: ${{ inputs.pr-number }}
        CONTEXT_PR_NUMBER: ${{ github.event.number }}
      with:
        script: |
          const body = process.env.PR_BODY;
          const prNumber = process.env.INPUT_PR_NUMBER || process.env.CONTEXT_PR_NUMBER;                    
          await github.rest.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber,
            body: body
          });
